AWSTemplateFormatVersion: "2010-09-09"
Description: Application Load Balancer stack for NT548 Lab 2

Parameters:
  ProjectName:
    Type: String
    Default: group7-cfn
    MaxLength: 20

  VpcId:
    Type: AWS::EC2::VPC::Id

  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id

  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id

  AlbSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id

  Worker1InstanceId:
    Type: String

  Worker2InstanceId:
    Type: String

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Type: application
      IpAddressType: ipv4
      SecurityGroups:
        - !Ref AlbSecurityGroupId
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-k3s-alb"

  K3sTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckEnabled: true
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher:
        HttpCode: "200"
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-k3s-tg"

  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref K3sTargetGroup

  Worker1TargetAttachment:
    Type: AWS::ElasticLoadBalancingV2::TargetGroupAttachment
    Properties:
      TargetGroupArn: !Ref K3sTargetGroup
      TargetId: !Ref Worker1InstanceId
      Port: 80

  Worker2TargetAttachment:
    Type: AWS::ElasticLoadBalancingV2::TargetGroupAttachment
    Properties:
      TargetGroupArn: !Ref K3sTargetGroup
      TargetId: !Ref Worker2InstanceId
      Port: 80

Outputs:
  AlbDnsName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  TargetGroupArn:
    Value: !Ref K3sTargetGroup
