apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: microservices
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: sagelms
data:
  SERVER_PORT: "8081"
  SPRING_PROFILES_ACTIVE: "default"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "sagelms"
