apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservices
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/part-of: sagelms
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: auth-service
        app.kubernetes.io/part-of: sagelms
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: auth-service
          image: AUTH_IMAGE_PLACEHOLDER
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - configMapRef:
                name: auth-service-config
            - secretRef:
                name: db-app-secret
            - secretRef:
                name: app-shared-secret
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 600m
              memory: 768Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 10001
            runAsGroup: 10001
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
